LineLength:
  Description: 'Limit lines to 120 characters.'
  Max: 120

BracesAroundHashParameters:
  Enabled: false

DotPosition:
  Enabled: false

AlignParameters:
  EnforcedStyle: with_fixed_indentation
